name: insta_eats_core
description: 'A new Flutter package project.'
version: 0.0.1
homepage: null

environment:
   sdk: ^3.8.1
   flutter: '>=1.17.0'

dependencies:
   cloud_firestore: ^5.6.9
   equatable: ^2.0.7
   firebase_auth: ^5.6.0
   firebase_core: ^3.14.0
   flutter:
      sdk: flutter
   flutter_svg: ^2.1.0
   fpdart: ^1.1.1
   lottie: ^3.3.1
   responsive_framework: ^1.5.1

dev_dependencies:
   build_runner: ^2.4.15
   flutter_gen_runner: ^5.10.0
   flutter_lints: ^5.0.0
   flutter_test:
      sdk: flutter
   very_good_analysis: ^9.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/fonts/
      - assets/images/categories/
      - assets/images/icons/
      - assets/images/logo/
      - assets/images/splash-screen/
      - assets/lottie/
      - assets/sounds/
      - assets/svg/

   fonts:
      - family: Uber Move
        fonts:
           - asset: assets/fonts/UberMoveMedium.otf
             weight: 400
           - asset: assets/fonts/UberMoveBold.otf
             weight: 600

flutter_gen:
   output: lib/src/gen/
   assets:
      exclude:
         - assets/fonts/UberMoveMedium.otf
         - assets/fonts/UberMoveBold.otf
   integrations:
      flutter_svg: true
      lottie: true
